### ISSUE TITLE
Nor balanced or chaotic mod works.

### ISSUE THREAD

**Issue by Vlad-00003** [daviscook477/CustomClimb#2]
Well, the title says that.
I've never worked with mods for this game (personly never knew they existing), so I just followed the instruction in the readme. 

Then I opend the menu and using Chaos or Balance buttons - the gui with the modifier count selection apperas. But I can't press any button. Cancel, confirm - they does nothing...

Custom run works with no problem.

**Comment by daviscook477** [comment]
I'll try and take a look later today. It might be that if you have an older version of BaseMod you should download the latest release. If that doesn't work I'll test it.

**Comment by Vlad-00003** [comment]
I just started to mod the game today. Latest version of BaseMod was released 11 days ago. It's simply impossible. But I would re-download both - BaseMod and this one. Just in case.

**Comment by Vlad-00003** [comment]
HEY
1 thing just come to my mind. 
I'm from the translation team, so I'm playing on beta branch... this can also be a reason...

**Comment by daviscook477** [comment]
Beta branch is *not* supported by mods so that could definitely be it. :). If that doesn't work I'll take a look. I'll try to make it more clear that the beta branch is not supported right now.

**Comment by Vlad-00003** [comment]
Yeah... sorry about that. Just forgot that I'm on that branch...
Most of the mods I have working, except - using more that 1 custom char causes crashes upon starting the run.
Once again - sorry that I've spend your time =^-^=

**Comment by daviscook477** [comment]
No problem! Have fun with modding.
