### ISSUE TITLE
I have only 1 positive effect in the list...

### ISSUE THREAD

**Issue by Vlad-00003** [daviscook477/CustomClimb#4]
So. The title says it all.
In total I got only 11 run mods, insted of 17 existing.
What I have: Name (id)
+ Big Game Hunter(Elite Swarm)
+ Certain Future (Uncertain Future)
+ Lethality (-)
+ Binary (-)
+ Night Terrors (-)
+ Terminal (-)
+ Vintage (-)
+ Hoarder (-)
+ Cursed Run (-)
+ Midas (-)
+ Time Dilation (-) -- The only one positive effect.

And what I'm missing for some reason:
+ Heirloom (-)
+ Insanity (-)
+ Shiny (-)
+ All Star (Allstar)
+ Diverse (-)
+ Draft (-) --It's the new mod.

Mods installed:
+ ModTheSpire v2.5.0
+ BaseMod v2.3.1
+ CustomClimb v0.3.0

That's it. I have no idea why these mods aren't in the list, or then they dissapered...
Latest steam game version (main branch this time =P) 03-29-2018

*Sidenote*
I've just noticed that both Balanced and Chaotic mods dosn't work. Pressing confirm or cancle does nothing.
The console doesn't contain anything interesting even in the debug mod.

**Comment by daviscook477** [comment]
BaseMod does not support weekly patch 18 yet

**Comment by Vlad-00003** [comment]
Oh... I see... ¯\_(ツ)_/¯
