### ISSUE TITLE
Game Crashes upon Choosing Merchant

### ISSUE THREAD

**Issue by ThisIsSoNotMe** [daviscook477/CustomClimb#5]
Occurs regardless of modifiers on both Silent and Ironclad

12:07:34.685 INFO cards.CardGroup> ERROR: No cards left for type: POWER
12:07:34.775 INFO shop.ShopScreen> ROLL 98
12:07:34.775 INFO dungeons.AbstractDungeon> Returning RARE relic
12:07:34.781 INFO shop.ShopScreen> ROLL 49
12:07:34.781 INFO dungeons.AbstractDungeon> Returning UNCOMMON relic
12:07:34.785 INFO shop.ShopScreen> ROLL 61
12:07:34.785 INFO dungeons.AbstractDungeon> Returning COMMON relic
12:07:34.790 INFO basemod.BaseMod> postCreateShopRelics for: [com.megacrit.cardcrawl.shop.StoreRelic@29b277d8, com.megacrit.cardcrawl.shop.StoreRelic@b33eff6, com.megacrit.cardcrawl.shop.StoreRelic@6440dece]
12:07:34.794 INFO basemod.BaseMod> postCreateShopPotions for: [com.megacrit.cardcrawl.shop.StorePotion@440e822d, com.megacrit.cardcrawl.shop.StorePotion@474d8e85, com.megacrit.cardcrawl.shop.StorePotion@10a105d4]

**Comment by bd94** [comment]
Why did you close this issue? Do you have a fix? I'm having this same problem.

**Comment by daviscook477** [comment]
I wasn't able to reproduce this. Is this still a problem with latest version of BaseMod and CustomClimb?
